### ISSUE TITLE
Fantastic work, theme changer - color

### ISSUE THREAD

**Issue by papyr** [WebVella/TagHelpers#1]
Hi, this is beautiful work 🥇 , just fantastic 👍 💯 I see you also updated to core 3.1!

Guys this is the **BEST** one out there since its true **tag helpers**

Will it work with other admin themes that use bootstrap?

1. Will it do href bread crumbs, timelines, d3
2. Can you also show a dashboard page with drag drop widgets
3. can you show us how to change the theme colors from user change. 
4. When user chooses top navigation, how to loading changing the style sheet colors 

thanks

**Comment by bzashev** [comment]
Hey thanks for the kind words, always appriciated.
It is a general bootstrap CSS plus some tweaking from my end. 
It should work with other admin themes, you can tweak what is loaded and what is not with the wv-include tag helper.
We are about to make more improvement in the library the next months mostly localization. Theme support is currently missing as they are pretty straightforward implementation. In most cases cover our needs in our App that we are developing.
Drag and drops are not present currently, but they are not that hard to be implemented, especially with JS components.
Breadcrumbs are not present or d3 support(we work with echarts, which I think are better)
We probably have  a long way until this can be a proper library, so all ideas are most than welcome
Cheers,
Boz

**Comment by bzashev** [comment]
I question back for you,
we are planing to work on a Blazor version too. Do you think it can be useful for you?
Boz

**Comment by weedkiller** [comment]
👍 for theme layout color and blazor (but still not as prevelant)
