### ISSUE TITLE
Operator '&&' cannot be applied to operands of type 'bool' and 'string'

### ISSUE THREAD

**Issue by 628426** [WebVella/TagHelpers#3]
I receive the following error in a page into which I've placed a FieldSelect component, with the FieldMode Display

RuntimeBinderException: Operator '&&' cannot be applied to operands of type 'bool' and 'string'
CallSite.Target(Closure , CallSite , object , object )
System.Dynamic.UpdateDelegates.UpdateAndExecute2<T0, T1, TRet>(CallSite site, T0 arg0, T1 arg1)
WebVella.TagHelpers.TagHelpers.WvFieldSelect.ProcessAsync(TagHelperContext context, TagHelperOutput output)
Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, int i, int count)
AspNetCore.Components_PcFieldSelect_Display.ExecuteAsync() in Display.cshtml
    31: is-visible="(bool)ViewBag.IsVisible" ajax-datasource="@options.AjaxDatasource.ToWvSelectOptionsAjaxDatasource()" select-match-type="@options.SelectMatchingType">

Although the line numbers aren't straightforward to follow, I had a look at the source and found this line which a) doesn't look like it would compile and b) looks like if it were somehow executed, would generate an error very similar to the above.

https://github.com/WebVella/TagHelpers/blob/2bc2b0b1d30cfdef20736bb5d6dfeba030ca3d05/WebVella.TagHelpers/TagHelpers/WvFieldSelect/WvFieldSelect.cs#L460

**Comment by bzashev** [comment]
You are correct. It is fixed now, Sync and thanks for the help!
